version: '3.8'

services:
  bd:
    image: "postgres:9.6-alpine"
    restart: unless-stopped
    ports:
      - 5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    env_file: docker-app/config/.env

  web:
    build: .
    restart: on-failure:3
    volumes:
    - .:/usr/src/app
    - ./logs:/usr/src/app/logs
    env_file:
      - docker-app/config/.env
    command: python manage.py runserver 0.0.0.0:8000
    ports:
    - 8000:8000
    depends_on:
      - bd
      - redis

  celery:
    build: .
    command: celery -A BankSubscriberAccount worker -l INFO
    volumes:
      - .:/usr/src/app/
    env_file:
      - docker-app/config/.env
    depends_on:
      - web
      - redis

  redis:
    image: "redis:alpine"


volumes:
  pgdata:
  logs: