# Generated by Django 3.2 on 2021-04-11 20:09

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='User uuid')),
                ('owner_name', models.CharField(max_length=128, verbose_name='Account owner fullname')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Account balance')),
                ('hold', models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Account hold bankroll (cash)')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSE', 'Close')], max_length=5, verbose_name='Account status')),
            ],
            options={
                'verbose_name': 'Bank account',
                'verbose_name_plural': 'Bank accounts',
            },
        ),
    ]
